name: Build Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  log-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "Verificação se o repositório está atualizado"
    - run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "O repositório está atualizado."
        else
          echo "O repositório não está atualizado."
          exit 1
        fi # Verifica se o repositório está atualizado


        